runtime: nodejs
#runtime: nodejs10
env: flex

manual_scaling:
  instances: 1

handlers:
- url: .*
#- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

endpoints_api_service:
  name: fonedef.appspot.com
  rollout_strategy: managed

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10