#runtime: nodejs
runtime: nodejs10
#env: flex
service: default

manual_scaling:
  instances: 1

handlers:
- url: .*
  secure: always
  script: auto

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10